server:
  port: 9595

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.52:5432/instagram_db
    username: postgres
    password: behdad2012


  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: false

minio:
  bucket:
    name: snappfood
  default:
    folder: "/"
  access:
    name: minioadmin
    secret: minioadmin

  url: http://127.0.0.1:9000